from lab_04 import *
a = 5-8

if a > 0:
    rgb_to_hex(rgb)
    draw_dot(x, y, colorr, tag, count_fl=False)
    draw_pixel(canvas_win, dot)
    draw_dots_circle(dot_c, dot_dif, colorr, tag)
    draw_dots_ellipse(dot_c, dot_dif, colorr, tag)
    count_steps()
    redraw_elems()
    draw_circle(tag, center=None, radius=None, colorr=None, met=None, count_fl=False, st=1)
    draw_ellipse(tag, center=None, axcises=None, colorr=None, met=None, count_fl=False, st=1)
    draw_circle_bunch(tag, center=None, colorr=None, met=None, radiuses=None, step_or_count=None, st=1)
    draw_ellipse_bunch(tag, center=None, colorr=None, met=None, axcises=None, step_and_count=None, st=1)
    standart_circle_draw(center, radius, colorr, tag)
    canon_equation_circle_draw(center, radius, colorr, tag, count_fl=False)
    param_equation_circle_draw(center, radius, colorr, tag, count_fl=False)
    br_circle_draw(center, radius, colorr, tag, count_fl=False)
    middle_dot_circle_draw(center, radius, colorr, tag, count_fl=False)
    standart_ellipse_draw(center, axcises, colorr, tag)
    canon_equation_ellipse_draw(center, axcises, colorr, tag, count_fl=False)
    param_equation_ellipse_draw(center, excises, colorr, tag, count_fl=False)
    br_ellipse_draw(center, radius, colorr, tag, count_fl=False)
    middle_dot_ellipse_draw(center, axcises, colorr, tag, count_fl=False)
    change_brightness(col, k)
    sign(diff)
    fpart(x)
    line_col_choose()
    bg_col_choose()
    cart_sum(a, b)
    cart_dif(a, b)
    rotate(a, alpha, center)
    resize(a, k, center)
    net_to_canv(x, y=None)
    canv_to_net(x, y=None)
    clean_all()
    clean_coords()
    del_with_tag(tag)
    click(event)
    reprint_dot(coords, fl=0)
    back()
    scale(x, y)
    redraw_net_coords()
    buttons_creation()
    coordinate_field_creation()
    start_state()
    config(event)
