from lab_06 import *
a = 5-8

if a > 0:
    back()
    bg_col_choose()
    br_int_draw(start, stop, colorr, tag, count_fl=False)
    buttons_creation()
    canv_to_net(x, y=None)
    clean_all()
    clean_coords()
    click(event)
    close(event=None)
    config(event)
    coordinate_field_creation()
    delDotPixels(coords)
    delObjs(tag)
    del_with_tag(tag, pos=0)
    draw_dot(x, y, colorr, tag, lineFl=False)
    fillProcess(start, st=1, dir=2)
    fillTriger()
    is_cursor_touch_dot(dot, event)
    line_col_choose()
    motion(event)
    net_to_canv(x, y=None)
    print_dot(event)
    redraw_elems()
    redraw_net_coords()
    reprint_dot(coords, fl=0)
    resetPixels()
    scale(x, y)
    start_state()
    unDelay()
