from lab_08 import *
a = 5-8

if a > 0:
    back()
    bg_col_choose()
    buttons_creation()
    canv_to_net(x, y=None)
    clean_all()
    clean_coords()
    click(event)
    close(event=None)
    config(event)
    coordinate_field_creation()
    cyrusbeck(cut, line, normals)
    del_with_tag(tag, pos=0)
    get_normal(dot_start, dot_end, dot_check)
    get_normals(cut)
    get_scalar_mul(fvector, svector)
    get_vect(dot_start, dot_end)
    get_vect_mul(fvector, svector)
    isCutterConvex(cutter)
    line_col_choose()
    motion(event, fl=0)
    motionWithShift(event)
    net_to_canv(x, y=None)
    redraw_elems()
    redraw_net_coords()
    scale(x, y)
    start_state()
