from lab_08 import *
a = 5-8

if a > 0:
    back()
    bg_col_choose()
    br_int_draw(start, stop, colorr, tag, count_fl=False)
    buttons_creation()
    canv_to_net(x, y=None)
    check_cut(cut)
    clean_all()
    clean_coords()
    click(event)
    close(event=None)
    config(event)
    coordinate_field_creation()
    cutterDraw()
    cyrusbeck(cut, section, normals, tag)
    deepCpy(arr1)
    delDotPixels(coords)
    delObjs(tag)
    del_with_tag(tag, pos=0)
    draw_dot(x, y, colorr, tag, lineFl=False)
    fillProcess(start, st=1, dir=2)
    fillTriger()
    get_distance(dot_start, dot_end)
    get_normal(dot_start, dot_end, dot_check)
    get_normals(cut)
    get_scalar_mul(fvector, svector)
    get_vect(dot_start, dot_end)
    get_vect_mul(fvector, svector)
    isCutterConvex(cutter)
    is_cursor_touch_dot(dot, event)
    lineDraw()
    line_col_choose()
    midpointcut(cutter, dot_start, dot_end, eps, tag)
    motion(event, fl=0)
    motionWithShift(event)
    net_to_canv(x, y=None)
    print_dot(event)
    redraw_elems()
    redraw_net_coords()
    reprint_dot(coords, fl=0)
    resetPixels()
    scale(x, y)
    set_code(dot, cut)
    start_state()
    unDelay()
    updateDots(dot1, dot2)
