from lab_09 import *
a = 5-8

if a > 0:
    back()
    bg_col_choose()
    buttons_creation()
    canv_to_net(x, y=None)
    check_vis(point, dot_start, dot_end)
    clean_all()
    clean_coords()
    click(event)
    close(event=None)
    config(event)
    coordinate_field_creation()
    cut_area(cutter, figure)
    del_with_tag(tag, pos=0)
    get_intersection(section, edge, normal)
    get_lines_parametric_intersec(line1, line2, normal)
    get_normal(dot_start, dot_end, dot_check)
    get_scalar_mul(fvector, svector)
    get_sections(section, points)
    get_vect(dot_start, dot_end)
    get_vect_mul(fvector, svector)
    isCutterConvex(cutter)
    is_in_section(point, section)
    is_visible(dot, f_dot, s_dot, other)
    line_col_choose()
    motion(event, fl=0)
    motionWithShift(event)
    net_to_canv(x, y=None)
    redraw_elems()
    redraw_net_coords()
    rgb_to_hex(rgb)
    scale(x, y)
    setNull()
    start_state()
    sutherland_hodgman_algorythm(cutter_line, dot3, position, prev_result)
